### ISSUE TITLE
rcc robot wrap ingore not worked

### ISSUE THREAD

**Issue by dogewzy** [robocorp/rcc#39] opened 2022-11-23 11:27 UTC
rcc version:11.30.0

command: rcc robot wrap -i conda.yaml --debug

![image](https://user-images.githubusercontent.com/11831143/203535253-f6356047-6081-4d8f-b9b7-c4d512ae4368.png)
ignore not workd 

the conda.yaml file still exists in zip file

**Comment by dogewzy** [comment] 2022-11-23 11:34
> 

the log("[D] - conda.yaml size 366") is produced by zipper.Add function

**Comment by vjmp** [comment] 2022-11-23 13:47
That `--ignore` option is for giving ignorance specification files, not ignoring those files. So it is these, but from command line: https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-are-ignorefiles

Other thing is, that you should never try to create robot.zip without `conda.yaml` if that file is used in your `robot.yaml`

So not a bug, but mistake in usage. Would propose to closing this issue.

**Comment by dogewzy** [comment] 2022-11-24 02:45
I just take "conda.yaml" for example.
`Patterns are like git ignore patterns but less powerful`
I have try the following action to remove **README.md** in my robot.zip:

1.rcc robot wrap -i *.md --debug
result: 
![image](https://user-images.githubusercontent.com/11831143/203682406-86cf9ed7-63ac-41aa-93be-3fc450433951.png)

2. rcc robot wrap -i README.md --debug
![image](https://user-images.githubusercontent.com/11831143/203682474-f51d8e0c-1bdd-4399-b7bd-cb443bd2a98e.png)


So what should I do if I want to skip the README.md file(or all the md file)

**Comment by dogewzy** [comment] 2022-11-24 02:52
And I also tried to ignore dir, not succeed:
![image](https://user-images.githubusercontent.com/11831143/203683474-51c4d9f9-72e1-446f-bd3f-32e6b0235684.png)

**Comment by dogewzy** [comment] 2022-11-24 02:53
And here is my project structure:
![image](https://user-images.githubusercontent.com/11831143/203683640-682e0e49-1adb-44c2-bdcb-d5b78433b64c.png)

**Comment by vjmp** [comment] 2022-11-24 07:03
Do not give patterns in command line. Write them in file, like "myignorefile". Then with command line, you give `--ignore myignorefile` and then those are ignored.

**Comment by dogewzy** [comment] 2022-11-24 07:06
> 

thank you! It worked!

**Comment by vjmp** [comment] 2022-11-24 08:00
@dogewzy can you now consider closing this?

**Comment by vjmp** [comment] 2022-11-25 13:01
Since no additional info or objections. I'll close this for now.

**Closed by vjmp** 2022-11-25 13:01 UTC
